
apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  type: NodePort
  ports:
  - port: 9001
    nodePort: 31234
    targetPort: 9000
  selector:
    app: sonar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar
        image: 168429521373.dkr.ecr.us-east-1.amazonaws.com/umsl:sonarqube
        ports:
        - containerPort: 9000
